### ISSUE TITLE
proot i/o error

### ISSUE THREAD

**Issue by zhanghua000** [MFDGaming/ubuntu-in-termux#10]
When I run vncserver on Huawei Honor device, the console terminates vncserver (i can't connect remote desktop) and output proot i/o error message like this:
![Screenshot_20190515_090301_com termux](https://user-images.githubusercontent.com/17194552/57743715-c45e6b80-76f8-11e9-92ab-7670ccdf7319.jpg)
However, when i do same thing on ubuntu 18.04 in termux, it runs normally and i can connect successfully.
Can anybody help me? thanks.

**Comment by MFDGaming** [comment]
Dud you install vnc correctly on ubuntu?

**Comment by MFDGaming** [comment]
What is your architecture?

**Comment by MFDGaming** [comment]
- [x]

**Comment by MFDGaming** [comment]
![](https://i.imgur.com/hW9mq8g.png)

**Comment by MFDGaming** [comment]
![](https://i.imgur.com/Dm5zxYE.png)

**Comment by MFDGaming** [comment]
For me it is working

**Comment by zhanghua000** [comment]
My CPU architecture is arm64(Hisilicon Kirin 970)
@MFDGaming

**Comment by MFDGaming** [comment]
what android version?

**Comment by MFDGaming** [comment]
Try reinstalling proot in the way i will tell you

**Comment by MFDGaming** [comment]
apt-get purge proot -y
apt-get install wget
wget http://termux.net/dists/stable/main/binary-arm/proot_5.1.107-21_arm.deb
dpkg --add-architecture arm
apt-get install proot_5.1.107-21_arm.deb

**Comment by MFDGaming** [comment]
@zhanghua000

**Comment by zhanghua000** [comment]
Now termux gives me these messages:

# u0_a238 @ localhost in ~/ubuntu-in-termux on git:master x [13:09:07]
$ ./start.sh
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

And what's worse, I can not start ubuntu.
My Android version is Android Pie
@MFDGaming

**Comment by diehard88** [comment]
pie killed proot.

**Comment by MFDGaming** [comment]
Just reinstall ubuntu-in-termux but install proot with the above steps

**Comment by MFDGaming** [comment]
pkg install git wget -y
apt-get purge proot -y
wget http://termux.net/dists/stable/main/binary-arm/proot_5.1.107-21_arm.deb
dpkg --add-architecture arm
apt-get install ./proot_5.1.107-21_arm.deb
cd ~
git clone http://github.com/MFDGaming/ubuntu-in-termux.git
cd ubuntu-in-termux
chmod +x *
./ubuntu.sh

**Comment by MFDGaming** [comment]
@zhanghua000

**Comment by MFDGaming** [comment]
If it doesn't work I am sending you to a grate app that will work 100% https://play.google.com/store/apps/details?id=tech.ula

**Comment by diehard88** [comment]
@MFDGaming 

my device is arm64.
the above will force install proot as arm.
will it work?

**Comment by zhanghua000** [comment]
Thanks, reinstalling ubuntu-in-termux is useless. Finally it's your app works.@MFDGaming

**Comment by diehard88** [comment]
@zhanghua000 

is your device pie?

**Comment by zhanghua000** [comment]
yes @diehard88

**Comment by diehard88** [comment]
@zhanghua000 

last question:   is your device arm or arm64?

**Comment by zhanghua000** [comment]
arm64 @diehard88

**Comment by MFDGaming** [comment]
@zhanghua000 did it finally work?

**Comment by zhanghua000** [comment]
No, termux outputs the same error messages. Your APP works well. @MFDGaming

**Comment by MFDGaming** [comment]
@zhanghua000 The app is not mine

**Comment by zhanghua000** [comment]
OK, anyway, thanks for your help. @MFDGaming

**Comment by MFDGaming** [comment]
@zhangua000 No problen

**Comment by Smarty10** [comment]
Having the same issue plz help... Cant open Ubuntu . It says...
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by rahuh489kmr** [comment]
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --hel

**Comment by rahuh489kmr** [comment]
help me.
And how to fix this problem. Please help a little bit.

**Comment by RanjithKumarS2002** [comment]
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`

Android 11 😞

**Comment by RanjithKumarS2002** [comment]
> proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
> proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
> proot info: default working directory is now "/"
> proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
> fatal error: see `proot --help`
> 
> Android 11 😞



Please help me with this, thank you
