### ISSUE TITLE
Much of error because ubuntu version 21.04

### ISSUE THREAD

**Issue by AlifAbhiesa** [MFDGaming/ubuntu-in-termux#103]
How can i install ubuntu with spesific version?
I want to install 20.04 version

**Comment by Juancarlo577** [comment]
You can go into the script and change the UBUNTU_VERSION=21.04 value to UBUNTU_VERSION=20.04 also if you want other versions thats available go to the Ubuntu repo and pick the version you want and add the version value into the script
