### ISSUE TITLE
Sudo command not found

### ISSUE THREAD

**Issue by jpvasoya** [MFDGaming/ubuntu-in-termux#105]
Sudo command not on bash. 
When I am trying to download sudo then sudo not locate.

**Comment by avenbreaks** [comment]
same, but Im trying apt <command> works

**Comment by CliveKBinu** [comment]
I think its beacuse ubuntu is running as root user, and you dont need sudo when u r running as root user. Its the same in my case too. My question will be is there any way to exit as a root user and return to normal user.

**Comment by domutala** [comment]
you have to install it `apt-get install sudo`
