### ISSUE TITLE
question about proot & pie

### ISSUE THREAD

**Issue by diehard88** [MFDGaming/ubuntu-in-termux#11]
I'm a bit confused.

after my note 8 was upgraded to pie, all my proot ubuntu installations were broken, as I couldn't  "_apt update_" anymore.  l was told it was proot.

To my surprise, I installed your ubuntu and everything is working fine....

**Comment by MFDGaming** [comment]
I don't know because i never had android pie (9). I only had android Ice cream sandwich (4.0.4) and android marshmallow (6.0)

**Comment by MFDGaming** [comment]
@diehard88
