### ISSUE TITLE
(I fixed it) Run Script ./ubuntu.sh is not working

### ISSUE THREAD

**Issue by BinithSingh** [MFDGaming/ubuntu-in-termux#12]
MFDGaming, i am getting an issue during 
Runing the script ./ubuntu.sh . It show's unknown architecture.
My architecture is i686

**Comment by MFDGaming** [comment]
i will fix it

**Comment by MFDGaming** [comment]
fixed

**Comment by MFDGaming** [comment]
i will soon close the issue

**Comment by MFDGaming** [comment]
@BinithSingh I FIXED IT
