### ISSUE TITLE
Fix resolv.conf is not working 

### ISSUE THREAD

**Issue by BinithSingh** [MFDGaming/ubuntu-in-termux#16]
MFDGaming  fix resolv.conf is not working.plz fix it .
![IMG_20190608_005534 (1)](https://user-images.githubusercontent.com/51412058/59156192-c546ab00-8ab4-11e9-943d-a97455986aa0.jpg)

**Comment by MFDGaming** [comment]
Please give me your architecture

**Comment by MFDGaming** [comment]
Reinstall termux and retry

**Comment by MFDGaming** [comment]
because the installation failed

**Comment by MFDGaming** [comment]
And it didnt download the rootfs

**Comment by BinithSingh** [comment]
I reinstalled termux  and followed same step but still it is not working. 
Plz fix it. If you want any information about my device, you just ask me
