### ISSUE TITLE
I can't connect this termux using ssh client

### ISSUE THREAD

**Issue by Siogian** [MFDGaming/ubuntu-in-termux#17]
I want to using ssh to connect to this ubuntu, but i failed.
using my pc with the same LAN, how can i do it?

thanks.

**Comment by MFDGaming** [comment]
https://github.com/MFDGaming/SSH-FOR-Ubuntu-In-Termux

**Comment by MFDGaming** [comment]
Try my ssh installer. By the way Good night it is 4:00am

**Comment by MFDGaming** [comment]
@Siogian

**Comment by Nyaasu66** [comment]
> https://github.com/MFDGaming/SSH-FOR-Ubuntu-In-Termux

where is it? it is 404 now.
