### ISSUE TITLE
Android 9 git tcsetattr Permission denied

### ISSUE THREAD

**Issue by markaljhon** [MFDGaming/ubuntu-in-termux#18]
Hi,
I got an error while installing git package using

**apt install git**

it says ...

> E: Setting in Start via TCSAFLUSH for stdin failed! - tcsetattr (13: Permission denied)

I hope you could help. Thanks.

**Comment by MFDGaming** [comment]
What architecture do you have

**Comment by MFDGaming** [comment]
@markaljhon

**Comment by MFDGaming** [comment]
@markaljhon Do you have android 8 or above?

**Comment by markaljhon** [comment]
@MFDGaming I have Android version 9 Arm.

**Comment by MFDGaming** [comment]
@markalojhon i am pretty shore that this is the problem because i have android 6.0 arm (armv7l)

**Comment by MFDGaming** [comment]
@markaljhon i am pretty shore that this is the problem because i have android 6.0 arm (armv7l)

**Comment by fragtion** [comment]
I'm curious why this issue was Closed without reason ? Is it because this is an Android-specific issue than a termux issue? At least stipulate so and if possible, provide a link to where this issue can be discussed further
