### ISSUE TITLE
VNC server

### ISSUE THREAD

**Issue by basel1996** [MFDGaming/ubuntu-in-termux#19]
How can I setup vnc server for ubuntu?
I have vncviewer and I made an account but it's always a black screen 

Edit: I tried this https://hackernoon.com/installation-of-vnc-server-on-ubuntu-1cf035370bd3 as recommended but it says it can't find those packages

**Comment by markaljhon** [comment]
try executing this on ubuntu terminal 

**apt update**

**Comment by basel1996** [comment]
@markaljhon I gave up on termux, I downloaded linux deploy and installed ubuntu from there

**Comment by markaljhon** [comment]
@basel1996 thank you for your response.

how's your experience with linux deploy?
does everything runs fine?

**Comment by basel1996** [comment]
@markaljhon yeah it's really good, no mistakes at all for now.
https://m.imgur.com/gallery/NHyXNmO

**Comment by markaljhon** [comment]
@basel1996 hmmm I think there's a problem with your imgur link.

I really want to see your setup.

**Comment by basel1996** [comment]
@markaljhon sorry this is the link 
.. https://imgur.com/gallery/c08cMDH

**Comment by markaljhon** [comment]
@basel1996 oh cool.
very nice setup.
what desktop environment is that?

**Comment by basel1996** [comment]
LXDE
It was the default one

**Comment by markaljhon** [comment]
@basel1996 thank you for your time.
you gave me ideas.
thanks.

**Comment by basel1996** [comment]
@markaljhon you're welcome :)

**Comment by MFDGaming** [comment]
If you need vnc use
`apt update && apt install tightvncserver && vncserver`
