### ISSUE TITLE
why symlink is not working

### ISSUE THREAD

**Issue by bensh4** [MFDGaming/ubuntu-in-termux#2]
I tried symlinking start.sh file to /bin
Still it can't start. The file is linked but can't execute. Can we make `start.sh` executable from anywhere? 
Thank you for the work!

**Comment by MFDGaming** [comment]
Yes

**Comment by MFDGaming** [comment]
1. wget https://archive.org/download/startubuntu/startubuntu
2. cp startubuntu /data/data/com.termux/files/usr/bin/

**Comment by MFDGaming** [comment]
Did this work for you???

**Comment by bensh4** [comment]
@MFDGaming 
No buddy,j actually removed Ubuntu because of this reason https://github.com/Neo-Oli/termux-ubuntu/issues/60 
Its a source bug. Any way good job from you!

**Comment by MFDGaming** [comment]
I know how to fix these stupid dpkg errors but i prefer not using ubuntu because it is pain in the ass with the dpkg errors.i prefer using debian10: https://github.com/MFDGaming/debian-in-termux/

**Comment by MFDGaming** [comment]
You may like it please try it. You can even add users! There are no dpkg errors as mutch as I have seen.

**Comment by bensh4** [comment]
@MFDGaming 
Hey, nice work buddy. Yes..I'll check it!

**Comment by MFDGaming** [comment]
Thanks

**Comment by bensh4** [comment]
@MFDGaming What'd be the size of debain after installation?

**Comment by bensh4** [comment]
@MFDGaming 
There 's a bug in your debain script while installing. The script is missing some permissions . So installation wasn 't complete.
It was keep saying *permission denied* .
 I 'm not opening an issue in that repo since your script is in beta stage. Fix it and release new version. Good luck :-)

**Comment by HackYardo** [comment]
Can the ubuntu run anywhere in termux now? The debian repo is gone and I can not link to the archive/startubuntu... I try `ln -s ubuntu.../startubuntu.sh asl`, and run ./asl, but it get `ubuntu-binds no such file or dir`, may I modify the startubuntu.sh? I am afraid something

**Comment by HackYardo** [comment]
Can the ubuntu run anywhere in termux now? The debian repo is gone and I can not link to the archive/startubuntu... I try `ln -s ubuntu.../startubuntu.sh asl`, and run ./asl, but it get `ubuntu-binds no such file or dir`, may I modify the startubuntu.sh? I am afraid something broken if I modify it.
