### ISSUE TITLE
Installation problem for i686

### ISSUE THREAD

**Issue by BinithSingh** [MFDGaming/ubuntu-in-termux#20]
![59156192-c546ab00-8ab4-11e9-943d-a97455986aa0-1-1](https://user-images.githubusercontent.com/51412058/60754724-032ae680-a003-11e9-91e2-6a59ba7de01d.jpg)
I reinstalled termux  and again tryed to install ubuntu.but its does't worked.I followed every step perfectly.plz fix it

**Comment by MFDGaming** [comment]
Did it skip any download?
Did it it extract correctly?

If you can’t give me more info I will need to help you with the team viewer app (team viewer is and app that you can control an others device)

**Comment by BinithSingh** [comment]
I have downloaded correctly. But i think extraction is not working perfectly.

**Comment by MFDGaming** [comment]
Try installing tar with: apt-get install tar

**Comment by MFDGaming** [comment]
@BinithSingh

**Comment by BinithSingh** [comment]
Tar is pre installed in my termux. 
![IMG_20190718_211035](https://user-images.githubusercontent.com/51412058/61512797-aa9f1480-aa18-11e9-9ddf-ad84e9e2b177.jpg)

**Comment by BinithSingh** [comment]
Can you solve this issue (proot info: vpid 1: terminated with signal 9) and plz tell me what it means.

**Comment by MFDGaming** [comment]
This thing happens because there are no rootfs. Look above that the download gets skipped

**Comment by BinithSingh** [comment]
So what should i do now???
I don't think there is any problem with download.

**Comment by MFDGaming** [comment]
It writes skipped download

**Comment by MFDGaming** [comment]
You can install it manually

**Comment by BinithSingh** [comment]
I have downloaded manually. But still getting an issue(proot info:vpid 1: terminated with signal 9).
