### ISSUE TITLE
Apt upgrade issue

### ISSUE THREAD

**Issue by ogahozy** [MFDGaming/ubuntu-in-termux#27]
how to I resolve this issue
Setting in Start via TCSAFLUSH for stdin failed! - tcsetattr (13: Permission denied)
Also I hope the dpkg warning doesn't do have:
Preparing to unpack .../archives/apt_1.8.1_arm64.deb ...
Unpacking apt (1.8.1) over (1.8.0) ...
dpkg: warning: symbolic link '/usr/lib/aarch64-linux-gnu/libapt-private.so.0.0' size has changed from 26 to 23
dpkg: warning: symbolic link '/usr/lib/apt/methods/https' size has changed from 18 to 4
dpkg: warning: symbolic link '/usr/lib/apt/methods/mirror+copy' size has changed from 18 to 6
dpkg: warning: symbolic link '/usr/lib/apt/methods/mirror+file' size has changed from 18 to 6
dpkg: warning: symbolic link '/usr/lib/apt/methods/mirror+ftp' size has changed from 18 to 6
dpkg: warning: symbolic link '/usr/lib/apt/methods/mirror+http' size has changed from 18 to 6
dpkg: warning: symbolic link '/usr/lib/apt/methods/mirror+https' size has changed from 18 to 6
dpkg: warning: symbolic link '/usr/lib/apt/methods/ssh' size has changed from 18 to 3
dpkg: warning: symbolic link '/usr/lib/apt/planners/dump' size has changed from 18 to 15
dpkg: warning: symbolic link '/usr/share/doc/apt/NEWS.Debian.gz' size has changed from 34 to 31
dpkg: warning: symbolic link '/usr/share/doc/apt/changelog.gz' size has changed from 34 to 29
Setting up apt (1.8.1) ...

**Comment by MFDGaming** [comment]
Have you change stuff in the Ubuntu file system?

For me it works perfectly
