### ISSUE TITLE
Access sdcard or storage  from the root@localhost:~#

### ISSUE THREAD

**Issue by ogahozy** [MFDGaming/ubuntu-in-termux#28]
Pls how do I access my system storage or sdcard from the ubuntu terminal. 
root@localhost:~# ls -la
total 40
drwx------.  2 root root 4096 Aug 31 07:11 .
drwx------. 21 root root 4096 Aug 31 09:10 ..
-rw-------.  1 root root  148 Aug 31 09:01 .bash_history
-rw-------.  1 root root 3106 Aug  6  2018 .bashrc
-rw-------.  1 root root  148 Aug  6  2018 .profile
root@localhost:~#
Just like this in the termux terminal 
root@localhost:~# exit
logout
$ cd
$ pwd
/data/data/com.termux/files/home
$ ls
storage  ubuntu
$

**Comment by ogahozy** [comment]
I got this solved
root@localhost# cd /storage 


> Pls how do I access my system storage or sdcard from the ubuntu terminal.
> root@localhost:~# ls -la total 40 drwx------. 2 root root 4096 Aug 31 07:11 . drwx------. 21 root root 4096 Aug 31 09:10 .. -rw-------. 1 root root 148 Aug 31 09:01 .bash_history -rw-------. 1 root root 3106 Aug 6 2018 .bashrc -rw-------. 1 root root 148 Aug 6 2018 .profile root@localhost:~#
> Just like this in the termux terminal
> root@localhost:~# exit
> logout
> $ cd
> $ pwd
> /data/data/com.termux/files/home
> $ ls
> storage ubuntu
> $

I got this solved
root@localhost# cd /storage

**Comment by MFDGaming** [comment]
You do `cd /sdcard`

**Comment by MFDGaming** [comment]
@ogahozy
