### ISSUE TITLE
Add gui support

### ISSUE THREAD

**Issue by ogahozy** [MFDGaming/ubuntu-in-termux#29]
I want to run opencv with ubuntu. How do I add a gui support.

**Comment by MFDGaming** [comment]
There are 2 ways

**Comment by MFDGaming** [comment]
1. Install tightvncserver on termux and install a VNC viewer on your device
2. Use xserver xsdl that is an app on the playstore

**Comment by ogahozy** [comment]
- [ ] 

> 1. Install tightvncserver on termux and install a VNC viewer on your device
> 2. Use xserver xsdl that is an app on the playstore

Xserver is not working on android pi

**Comment by MFDGaming** [comment]
Ok

**Comment by MFDGaming** [comment]
I have android marshmallow
