### ISSUE TITLE
Ffmpeg mit working

### ISSUE THREAD

**Issue by kiam001** [MFDGaming/ubuntu-in-termux#3]
libx264 not found

**Comment by MFDGaming** [comment]
Probably it is not installed or it is not in the repo of ubuntu

**Comment by kiam001** [comment]
libx264 is installed.

permission denied is the error text

**Comment by kiam001** [comment]
you kan repudiation the error.
apt-get install ffmpeg -y
ffmpeg

**Comment by kiam001** [comment]
ffmpeg work on termux without Ubuntu

**Comment by MFDGaming** [comment]
I cant make it work because thats a problem that the ubuntu repo has and ot doesen't download ffmpeg correctly. I looked for it in google but the faut is thw ubuntu inux os

**Comment by kiam001** [comment]
what can I doing that it works.
maybe Route the termux ffmpeg to your ubuntu in termux
