### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by nitesh-mishr** [MFDGaming/ubuntu-in-termux#30]
When i type
$ ./start.sh
I get following error 

/usr/bin/env: '/bin/bash': No such file or directory
Can any one help me

**Comment by MFDGaming** [comment]
Can you give me more info

**Comment by MFDGaming** [comment]
@nitesh-mishr

**Comment by nitesh-mishr** [comment]
i have followed the command which were given in the respirotary


> Can you give me more info

I have followed the same command given by you in Repositorie and i get the error shown in photo 

- [ ] [
![Screenshot_20190911-182408_Termux](https://user-images.githubusercontent.com/46121792/64699563-acd69a00-d4c2-11e9-8ed6-b9f9af272458.jpg)
](url)

**Comment by Awakened-Redstone** [comment]
Same for me

**Comment by MFDGaming** [comment]
The problem is that your device is not downloading the stuff correctly. I have to check why it does not work on your device. (In mine it works) what architecture do you have?

**Comment by MFDGaming** [comment]
@pavankmr853

**Comment by MFDGaming** [comment]
@nitesh-mishr

**Comment by MFDGaming** [comment]
And sorry for not answering at the correct time. I was quite busy

**Comment by MFDGaming** [comment]
This issue is here for too long. I have to close it

**Comment by MFDGaming** [comment]
I

**Comment by nitesh-mishr** [comment]
Can you give me solution
I phone is j 7 prime

**Comment by MFDGaming** [comment]
@nitesh-mishr try it again with my new install script
