### ISSUE TITLE
I want create a Termux distro repo

### ISSUE THREAD

**Issue by KitsuneIDK** [MFDGaming/ubuntu-in-termux#34]
I want create a Termux repository with all distros available to download and I want modify and add your script

**Comment by MFDGaming** [comment]
If you want do it but please leave some credits

**Comment by MFDGaming** [comment]
@KitsuneIDK

**Comment by KitsuneIDK** [comment]
I gonna give credits to you

**Comment by MFDGaming** [comment]
Thank you

**Comment by MFDGaming** [comment]
Thank you
