### ISSUE TITLE
Just a random problem

### ISSUE THREAD

**Issue by jat28468** [MFDGaming/ubuntu-in-termux#35]
![Screenshot_20191107-205850_Termux](https://user-images.githubusercontent.com/57433751/68454271-1dc5d400-021e-11ea-9a2e-960771c5cc70.jpg)
please solve this problem  make a tutorial video on YouTube 
![Screenshot_20191107-205850_Termux](https://user-images.githubusercontent.com/57433751/68454271-1dc5d400-021e-11ea-9a2e-960771c5cc70.jpg)

**Comment by MFDGaming** [comment]
This link redirects me to the issue page so that means that you have to resend the screenshot

**Comment by MFDGaming** [comment]
First of all your doing something wrong. You have to wait for this process and not paste words on processes
