### ISSUE TITLE
Error: Invalid system call

### ISSUE THREAD

**Issue by Alexei1981** [MFDGaming/ubuntu-in-termux#37]
Hey.  A binary file compiled with static libraries in this Ubuntu, run in other applications only on android 5-7.  I tried to run the program compiled by gcc-9 from Ubuntu in another terminal emulator, it produces this error: invalid system call.  On android 6.0 marshmallow, everything works fine.  Is there any way to fix this?  Thanks.

**Comment by MFDGaming** [comment]
What other terminal emulator?

**Comment by MFDGaming** [comment]
@Alexei1981

**Comment by Alexei1981** [comment]
For example, this one:
https://play.google.com/store/apps/details?id=jackpal.androidterm

**Comment by MFDGaming** [comment]
Was it on the same device?

**Comment by MFDGaming** [comment]
@Alexei1981

**Comment by Alexei1981** [comment]
@MFDGaming 
Yes.  Lenovo tab v 7, Android  9, snapdragon 450.
I compiled an executable file with static libraries.  Interestingly, the binary file of the compiled program works well on android 6 and 7. Problems only in android 8 and 9. Outside the Ubuntu environment, static executable files do not run on android 8 and 9.

**Comment by Alexei1981** [comment]
Here I am compiling a simple program "Hello World"
`#include <stdio.h>

int main(int argc, char *argv[])
{
 printf("Hello, World!!!\n");
 return 0;
}
`
cc -O2 -Wall -flto   -c -o hello.o hello.c                  cc -o hello hello.o -static
And run in another application (outside of Ubuntu)
./hello                             Hello, World!!!

But when I built this program using the "build-essential" package:
https://github.com/syzygy1/Cfish
When it starts in another terminal application, it displays the following:
./cfish
Bad system call
159|
If you run this program in Ubuntu, then it works.  The program is compiled with static libraries
At the same time, everything works well on Android 6.

**Comment by Alexei1981** [comment]
I ran a program compiled in Ubuntu with static libraries in termux (without starting Ubuntu) and ran the strace utility.
 Here is the error log.
 
```

```

 
 execve("./cfish", ["./cfish"], 0x7ff776e480 /* 21 vars */) = 0
brk(NULL)                               = 0x19b1d000
brk(0x19b1df90)                         = 0x19b1df90
uname({sysname="Linux", nodename="localhost", ...}) = 0
set_tid_address(0x19b1d0d0)             = 7014
set_robust_list(0x19b1d0e0, 24)         = 431083744
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x42bc6c, si_syscall=__NR_set_robust_list, si_arch=AUDIT_ARCH_AARCH64} ---
+++ killed by SIGSYS +++

**Comment by MFDGaming** [comment]
It is probably because the one device is 64bit and the other 32bit

**Comment by Alexei1981** [comment]
@MFDGaming 
Not.  Both devices are 64 bits.

**Comment by MFDGaming** [comment]
@Alexei1981 so that's the problem

**Comment by MFDGaming** [comment]
Both of them have to have the same architecture (strictly).

**Comment by MFDGaming** [comment]
So I am going to close this issue
