### ISSUE TITLE
Error: mount: /sys/fs/cgroup: permission denied.

### ISSUE THREAD

**Issue by haswelliris** [MFDGaming/ubuntu-in-termux#38]
When I tried to start `docker` service, it's  failed and got a error message "mount: /sys/fs/cgroup: permission denied.".  
commands to reproduce
```
apt-get update
apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu disco stable"
apt install docker-ce docker-ce-cli
service docker start
```
It seems like I cannot change `/sys/fs/cgroup` in ubuntu-in-termux.  And I found `command+=" -b /sys"` in `ubuntu.sh` which means `/sys` is linked to the real adroid system directory.   
I want to know if I can ONLY set `/sys/fs/cgroup` to a temp directory that can be changed by user.  
As android's kernel doesn't provide cgroups support, this change actually does not take effect to system but it can solve the problem such as lacking of some cgroups.  
  
Device Info
```
Qualcomm Snapdragon 821 (MSM 8996 Pro)
Android 9.0 (Mokee ROM)
Linux localhost 3.18.140-mokee-g32d4dd5ec223 #1 SMP PREEMPT Sun Jan 5 03:53:43 CST 2020 aarch64 aarch64 aarch64 GNU/Linux
ubuntu19.10-in-termux
```

**Comment by MFDGaming** [comment]
Try it again by uncomenting this `command+=" -b /sys"` line by doing:

`#command+=" -b /sys"`

**Comment by MFDGaming** [comment]
@haswelliris
