### ISSUE TITLE
Missing i386 base image for Ubuntu 20.04

### ISSUE THREAD

**Issue by m-ueberall** [MFDGaming/ubuntu-in-termux#40]
Line 32 of `ubuntu.sh` as shown below should be replaced by a conditional/an error message stating that there is no usable base image for architecture `i386` (at least as of Ubuntu 20.04, older releases should still work): https://github.com/MFDGaming/ubuntu-in-termux/blob/b19489a509df6691cc0eea836245df7415c17557/ubuntu.sh#L32

**Comment by MFDGaming** [comment]
I’ll just let the people use Ubuntu 19.10 for i*86

**Comment by MFDGaming** [comment]
Or maybe no I’ll just remove it
