### ISSUE TITLE
Neofetch showing Incorrect uptime

### ISSUE THREAD

**Issue by dekubi** [MFDGaming/ubuntu-in-termux#42]
Neofetch shows incorrect uptime from booting time.
Any ways to correct that.
Again executing "uptime" raise error "/proc not mounted"

![Screenshot_20200428-174645](https://user-images.githubusercontent.com/16203077/80527439-e1309500-8983-11ea-8297-50dcc6befdbd.png)

**Comment by MFDGaming** [comment]
Proc can’t be mounted on newer versions of android (8 and up).
