### ISSUE TITLE
Basic commands not available once I'm root user

### ISSUE THREAD

**Issue by obriankevin11** [MFDGaming/ubuntu-in-termux#44]
Hi, 
I ran the commands without pb and I get "root@localhost:~#" when running the last one: ./startubuntu.sh

Pb: I don't even have nano installed anymore :
bash: nano: command not found

Do I have to reinstall all the packages? 

Thank you. 

Sorry for the possible dumb/linux newbie question :)

**Comment by MFDGaming** [comment]
Ubuntu-in-termux is a subsystem for termux so you have to install all the packages you need directly to Ubuntu-in-termux.
