### ISSUE TITLE
It has error when run ./startubuntu.sh

### ISSUE THREAD

**Issue by joytou** [MFDGaming/ubuntu-in-termux#45]
When I run `./startubuntu.sh`, it report such error:
```
$ ./startubuntu.sh
proot warning: can't sanitize binding "/sys": No such file or directory
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't sanitize binding "/sdcard": No such file or directory
proot warning: can't sanitize binding "/mnt": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
proot error: trying to remove a directory outside of '/data/data/com.termux/files/usr/tmp', please report this error.
```

**Comment by xuwlgo** [comment]
I also have this issue.So did you have solve it?

**Comment by joytou** [comment]
> I also have this issue.So did you have solve it?

Have not yet.

**Comment by MFDGaming** [comment]
This issue occurred because the rootfs don’t exist. Are you shore you had internet connection while installing it?

**Comment by Wahyu6070** [comment]
./startubuntu.sh
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
$

**Comment by Wahyu6070** [comment]
startubuntu.sh  ubuntu-fs
$ ./startubuntu.sh
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
$ ls
README.md       ubuntu-binds  ubuntu.sh
startubuntu.sh  ubuntu-fs
$

**Comment by devlocalhost** [comment]
I didn't had any issue while installing and running it, it works fine on my phone, I suggest you to reinstall it.

**Comment by Wahyu6070** [comment]
I found the problem turned out to be caused by ip, this can be overcome by using the VPN application

**Comment by MFDGaming** [comment]
ok
