### ISSUE TITLE
Android 10, "Permission denied" in a SD card

### ISSUE THREAD

**Issue by KangKazumi** [MFDGaming/ubuntu-in-termux#47]
Android 10 upgrade turned out to be such a bad idea because I lost the writing permission in my external SD card.

Is there a way to fix it?

**Comment by CipherMk** [comment]
Just force delete the whole package.......

$rm - r ubuntu-in-termux

**Comment by KangKazumi** [comment]
What do you mean?

**Comment by CipherMk** [comment]
Remove the whole set up.
Look for another option to run Ubuntu

**Comment by KangKazumi** [comment]
In fact, not only ubuntu, termux itself can not get write permission for sd card in Android 10.

**Comment by MFDGaming** [comment]
That’s true use userland I think it may suit you
