### ISSUE TITLE
Bash inatall.sh not working Says No Internet met connection any solution? Please Help

### ISSUE THREAD

**Issue by superman-enamy** [MFDGaming/ubuntu-in-termux#49]
Bash inatall.sh not working Says No Internet met connection any solution? Please Help

**Comment by MFDGaming** [comment]
Are you shore you have internet?

**Comment by superman-enamy** [comment]
> Are you shore you have internet?

Yes bro i Connected with internet

**Comment by hackingjoy** [comment]
**** NMAP NOT WORKING.


Starting Nmap 7.80 ( https://nmap.org ) at 2020-06-25 17:31 UTC
nmap: netutil.cc:3265: int route_dst_netlink(const sockaddr_storage*, route_nfo*, const char*, const sockaddr_storage*): Assertion `p != NULL' failed.
Aborted

**Comment by hackingjoy** [comment]
NMAP NOT WORKING 
@MFDGAMING

Starting Nmap 7.80 ( https://nmap.org ) at 2020-06-25 17:31 UTC
nmap: netutil.cc:3265: int route_dst_netlink(const sockaddr_storage*, route_nfo*, const char*, const sockaddr_storage*): Assertion `p != NULL' failed.
Aborted

**Comment by MFDGaming** [comment]
@hackingjoy  Your android device has to be rooted in order to do that

**Comment by devlocalhost** [comment]
> Yes bro i Connected with internet
did you used mobile data??
if yes, try with wifi.
if you used wifi, then try with a different one, use another device or clear termux cache and data
