### ISSUE TITLE
What is the default password?

### ISSUE THREAD

**Issue by luxueyan** [MFDGaming/ubuntu-in-termux#5]
`chsh -s zsh` need input password, what is it?

**Comment by MFDGaming** [comment]
It has no password. You need to set it

**Comment by Luisdavid2204** [comment]
Hola no puedo instarlo me aparece $ git clone https://github.com/MFDGaming/ubuntu-in-termux.gi
Cloning into 'ubuntu-in-termux.gi'...
Username for 'https://github.com':  4ea79fd  on 20 Apr
Password for 'https:// 4ea79fd  on 20 Apr@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/MFDGaming/ubuntu-in-termux.gi/'

**Comment by MFDGaming** [comment]
You mad a mistake

**Comment by MFDGaming** [comment]
You typed `git clone https://github.com/MFDGaming/ubuntu-in-termux.gi` instead of
`git clone https://github.com/MFDGaming/ubuntu-in-termux.git`

**Comment by MFDGaming** [comment]
@Luisdavid2204
