### ISSUE TITLE
Fatal error proot help

### ISSUE THREAD

**Issue by charelbijhnesh** [MFDGaming/ubuntu-in-termux#51]
This is my error:proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
$

**Comment by Farhan-prog** [comment]
Same here
 Why is it come

**Comment by Farhan-prog** [comment]
$ ./startubuntu.sh
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by murden-dev** [comment]
same here.

**Comment by MFDGaming** [comment]
this error got fixed
