### ISSUE TITLE
Proof error

### ISSUE THREAD

**Issue by KoolSkins** [MFDGaming/ubuntu-in-termux#52]
Each time I try to do ./startubuntu.sh I get proot 
 error 
$ ./startubuntu.sh
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

I also tried connecting to a vpn it still doesn't work. Any fixes for this?

**Comment by NowanIlfideme** [comment]
Same here. Full trace:

```sh
$ chmod +x ubuntu.sh
$ ./ubuntu.sh -y
[02:46:44 AM] [WARNING]:  Skipping the download and the extraction
[02:46:44 AM] [Installer thread/INFO]:  Creating the start script, please wait...
[02:46:44 AM] [Installer thread/INFO]:  The start script has been successfully created!
[02:46:44 AM] [Installer thread/INFO]:  Fixing shebang of startubuntu.sh, please wait...
[02:46:44 AM] [Installer thread/INFO]:  Successfully fixed shebang of startubuntu.sh!
[02:46:44 AM] [Installer thread/INFO]:  Making startubuntu.sh executable please wait...
[02:46:44 AM] [Installer thread/INFO]:  Successfully made startubuntu.sh executable
[02:46:44 AM] [Installer thread/INFO]:  Cleaning up please wait...
[02:46:44 AM] [Installer thread/INFO]:  Successfully cleaned up!
[02:46:44 AM] [Installer thread/INFO]:  The installation has been completed! You can now launch Ubuntu with ./startubuntu.sh
$ ./startubuntu.sh
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
$
```

**Comment by J0sat** [comment]
help
`proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/coding/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.`

**Comment by J0sat** [comment]
help
` proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/coding/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`. `

**Comment by J0sat** [comment]
help
`proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/coding/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see ``proot --help``.`

**Comment by J0sat** [comment]
same
`proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/coding/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see` `proot --help``.`
