### ISSUE TITLE
Cannot open /proc/stat: Permission denied when accessing top and htop

### ISSUE THREAD

**Issue by amirhoseinsalimi** [MFDGaming/ubuntu-in-termux#7]
Hello,
I've noticed running `top` command produces:
`Cannot open /proc/stat`

After that, I installed htop and when I run it, it splits the same error:
`Cannot open /proc/stat`

This is my system information:
Linux localhost 4.4.23+ #1 SMP PREEMPT ... aarch64 aarch64 aarch64 GNU/Linux

**Comment by MFDGaming** [comment]
I will check it

**Comment by MFDGaming** [comment]
Your android os is at fault. I am sorry I can't help :(. With my device it works correctly. I have armv7l

**Comment by amirhoseinsalimi** [comment]
I don't think that my phone is to blame, cause in normal Termux mode `top` and `htop` work just fine.

**Comment by MFDGaming** [comment]
I dont know. For me it works.

**Comment by diehard88** [comment]
https://github.com/Neo-Oli/termux-ubuntu/issues/45

**Comment by MFDGaming** [comment]
I told him that the fault was android
