### ISSUE TITLE
Use the 20.04.2 image instead

### ISSUE THREAD

**Issue by apandada1** [MFDGaming/ubuntu-in-termux#80]
Canonical released Ubuntu 20.04.2 early this year, and they are available at https://cdimage.ubuntu.com/ubuntu-base/releases/20.04/release/

These images contain some updated packages over those present in 20.04.1.
They may soon delete the 20.04.1 images (just as they deleted the 20.04 images), and then the script would stop working.

**Comment by MFDGaming** [comment]
Fixed
