### ISSUE TITLE
Backing up

### ISSUE THREAD

**Issue by msn-05** [MFDGaming/ubuntu-in-termux#81]
How to backup ubuntu?
I tried compressing ubuntu-in-termux folder with tar but I get permission denied error.
So how to backup this folder without permission denied error??

**Comment by MFDGaming** [comment]
You should remove the proc, dev and sys folders from your ubuntu-fs folder to not get that error

**Comment by msn-05** [comment]
Won't i need those folders after restoring?

**Comment by MFDGaming** [comment]
Not really since they are just mounts
