### ISSUE TITLE
.startubuntu.sh

### ISSUE THREAD

**Issue by JohnathanAdams1990** [MFDGaming/ubuntu-in-termux#86]
What should I do?

root warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

Cited 

Termux [ubuntu-in-termux] (05/05/2021)
![Screenshot_20210705-120402_Termux](https://user-images.githubusercontent.com/86982202/124510663-2969f500-dd89-11eb-96a2-188a2f8a2c40.jpg)

**Comment by kiam001** [comment]
Hello, it looks Download faild l. Did you forgot Install wget? By me Works

**Comment by Woynert** [comment]
I encountered this issue too. The wget is trying to download a file that does not exists. The file in the ubuntu 18.04 page has the version 18.04.5 not just 18.04
Ubuntu base page: https://cdimage.ubuntu.com/ubuntu-base/releases/18.04/release/

So to fix it just fix the name file in line 40 to match the one in the website (https://github.com/MFDGaming/ubuntu-in-termux/blob/b4c021ed9fbce2c7d25f9f0db55ce7b7696992cb/ubuntu.sh#L40)

Original: wget http://cdimage.ubuntu.com/ubuntu-base/releases/${UBUNTU_VERSION}/release/ubuntu-base-${UBUNTU_VERSION}-base-${ARCHITECTURE}.tar.gz -q -O ubuntu.tar.gz 
Fixed: wget http://cdimage.ubuntu.com/ubuntu-base/releases/${UBUNTU_VERSION}/release/ubuntu-base-${UBUNTU_VERSION}.5-base-${ARCHITECTURE}.tar.gz -q -O ubuntu.tar.gz
