### ISSUE TITLE
dpkg-issue on package installation

### ISSUE THREAD

**Issue by Bearbobs** [MFDGaming/ubuntu-in-termux#87]
`error creating new backup file '/var/lib/dpkg/statoverride-old': Operation not permitted`

## Steps to reproduce:

`apt install htop`

**Comment by PaoloLRinaldi** [comment]
@Bearbobs  Did you find a solution?

**Comment by jhiberne** [comment]
(Not in termux but in Userland) I resolved the same error this way :

```sh
cp -p /var/lib/dpkg/statoverride-new /var/lib/dpkg/statoverride
```

**Comment by kjackson23** [comment]
> (Not in termux but in Userland) I resolved the same error this way :
> 
> cp -p /var/lib/dpkg/statoverride-new /var/lib/dpkg/statoverride

Thank you!  This worked in UserLAnd for me on 2025-03-18
