### ISSUE TITLE
problems when trying to install ubuntu.sh resolf.conf

### ISSUE THREAD

**Issue by TheAlmightyBreadbear** [MFDGaming/ubuntu-in-termux#9]
![image](https://user-images.githubusercontent.com/43274933/57174729-1ff84180-6e3b-11e9-9eb7-3bb94a6d9351.png)

**Comment by MFDGaming** [comment]
Your CPU is not supported

**Comment by MFDGaming** [comment]
Can you tell me what is your architecture sp so that I add it?

**Comment by MFDGaming** [comment]
Just tell me the results of this command

**Comment by MFDGaming** [comment]
dpkg --print-architecture

**Comment by BinithSingh** [comment]
I am also getting same issue during running the script.
My architecture is i686
Plzz bro, solve this issue

**Comment by MFDGaming** [comment]
FIXED
