### ISSUE TITLE
Apt update not working while using WIFI, but it works with mobile data

### ISSUE THREAD

**Issue by toufiqnuur** [MFDGaming/ubuntu-in-termux#90]
I'm trying to apt update and isn't working if using WiFi connection.

`Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/hirsute-updates/InRelease  Temporary failure resolving 'ports.ubuntu.com'`

**Comment by inilim** [comment]
@toufiqnuur How did you decide that?
