### ISSUE TITLE
How to setup storage permission

### ISSUE THREAD

**Issue by vishnudas-bluefox** [MFDGaming/ubuntu-in-termux#92]
I install this ubuntu thing before setting up storage permission how could I set the storage permission now termux-setup storage not working here how could I configure

**Comment by beki13** [comment]
you can found in /sdcard folder

**Comment by kiam001** [comment]
https://github.com/MFDGaming/ubuntu-in-termux/blob/1f587353bff3749d395479c5d8044d0bf1021f0b/ubuntu.sh#L87

So You internal storage is on /sdcard in you ubuntu
