### ISSUE TITLE
bash: /bin/vim: No such file or directory

### ISSUE THREAD

**Issue by beki13** [MFDGaming/ubuntu-in-termux#94]
i have installed vim.
but i cant run it.
the there is vim file in /bin folder but not reading it.

**Comment by MFDGaming** [comment]
Let me give it a test

**Comment by MFDGaming** [comment]
Vim works just fine for me

**Comment by mahaidong** [comment]
me too , I installed vim , but can not use it as root

**Comment by Ernestoo2** [comment]
so sorry do you still have issues
